server {

    listen 80;

    server_name localhost;

    # -------------------------
    # AUTH SERVICE
    # -------------------------

    location ^~ /api/auth/ {
        include fastcgi_params;

        fastcgi_pass auth_service:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/public;
    }

    location ^~ /api/internal/auth/ {
        include fastcgi_params;

        fastcgi_pass auth_service:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/public;
    }

    # -------------------------
    # CONVIE APPLICATION
    # -------------------------

    root /var/www/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {

        try_files $uri =404;

        fastcgi_pass convie:9000;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/public;
    }


    

}